#!/bin/sh

# Check whether tmux is installed
tmux_name=tmux
if ! command -v $tmux_name > /dev/null
then
    echo "$tmux_name is not installed"
    exit
fi

# Check if within tmux session
session_name=base
if [ -z "$TMUX" ]
then
    tmux attach -t $session_name || tmux new -s $session_name
fi
