#!/bin/sh

## Editor ##
alias v="$EDITOR"
alias sv="sudo $EDITOR"
alias zshrc="$EDITOR ~/.zshrc" # Quickly open zshrc
alias bashrc="$EDITOR ~/.bashrc" # Quickly open bashrc

## Built-in commands ##
alias ss="sudo systemctl"
alias mv="mv -iv"
alias rm="rm -iv"
alias cp="cp -iv"
alias grep="grep --color=auto"
alias ls='ls --color=auto -hF'
alias ll='ls -l'
alias c="clear"

## Package management ##
alias pls="sudo"
if command -v pacman > /dev/null; then
    alias ups="pls pacman -Syy"
    alias ins="pls pacman -S --noconfirm --needed"
    alias unins="pls pacman -Rns --noconfirm"
elif command -v apt > /dev/null; then
    alias ups="pls apt update"
    alias ins="pls apt install -y"
    alias unins="pls apt-get purge --auto-remove -y"
fi

## Git ##
alias ga="git add"
alias gs="git status"
alias gd="git diff"
alias gl="git log --oneline"
alias gpush="git push origin main"
alias gpull="git pull origin main"
alias gc="git commit"
alias gcs="git commit -S"

## Tmux ##
alias tmux="tmux -u"  # Allow unicode characters

## Bat ##
if command -v bat > /dev/null; then
    alias cat="bat -p"
fi
