#!/bin/sh

chmodf() {
        find $2 -type f -exec chmod $1 {} \;
}
chmodd() {
        find $2 -type d -exec chmod $1 {} \;
}

# Append our default paths
add_to_path () {
    case ":$PATH:" in
        *:"$1":*)
            ;;
        *)
           PATH="$1${PATH:+":$PATH"}"
    esac
}

if command -v fzf >/dev/null; then
    ff() {
      IFS=$'\n' files=($(fzf-tmux --query="$1" --multi --select-1 --exit-0))
      [[ -n "$files" ]] && ${EDITOR:-vim} -O "${files[@]}" -p
    }
fi


