#!/bin/sh

$UPDATE_COMMAND

if [ "$OS" = "arch" ]; then
    $INSTALL_COMMAND open-vm-tools
    # Arch
    $INSTALL_COMMAND xf86-input-vmmouse xf86-video-vmware mesa gtkmm3

else
    # Debian things
    $INSTALL_COMMAND open-vm-tools-desktop
fi

sudo systemctl start vmtoolsd
sudo systemctl enable vmtoolsd
sudo systemctl start vmware-vmblock-fuse
sudo systemctl enable vmware-vmblock-fuse
