format = """
$localip\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$time\
$line_break\
$jobs\
$status\
$character"""

[battery]
disabled=true

[directory]
fish_style_pwd_dir_length = 1
truncate_to_repo = false

[git_branch]
symbol = ""

[localip]
disabled = false
ssh_only = false

[time]
disabled = false
