#!/bin/sh
if [ $# -eq 0 ]
then
    printf "Email: "
    read email
else
    email="$1"
fi

ssh-keygen -t ed25519 -C "$email"
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_ed25519
cat ~/.ssh/id_ed25519.pub
